[sql_engine_events]
search = (sourcetype="WinEventLog:Application") AND (SourceName="MSSQLSERVER" OR SourceName="MSSQL$*")

[sql_agent_events]
search = (sourcetype="WinEventLog:Application") AND (SourceName="SQLSERVERAGENT" OR SourceName="SQLAgent$*")

[sql_service_events]
search = (sourcetype="WinEventLog:System") AND SourceName="Service Control Manager" AND (Message="*MSSQL*" OR Message="*SQL Server*")

[sql_custom_telemetry]
search = (sourcetype="WinEventLog:Application") AND SourceName="SQLAgentTelemetry"

[sql_all_events]
search = eventtype=sql_engine_events OR eventtype=sql_agent_events OR eventtype=sql_service_events OR eventtype=sql_custom_telemetry
